#
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
#

Name:       gdbm
Summary:    GNU Database Routines
Version:    1.8.3
Release:    1
Group:      System/Libraries
License:    GPL-2.0+
URL:        http://directory.fsf.org/GNU/gdbm.html
Source0:    http://ftp.gnu.org/pub/gnu/gdbm/gdbm-%{version}.tar.bz2
Source100:  gdbm.yaml
Patch0:     gdbm-%{version}.dif
Patch1:     gdbm-protoize_dbm_headers.patch
Patch2:     gdbm-prototype_static_functions.patch
Patch3:     gdbm-fix_testprogs.patch
Patch4:     gdbm-destdir.patch
Patch5:     gdbm-stamp.patch
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig


%description
A static and dynamic library for the GNU database routines.


%package devel
Summary:    Include Files and Libraries mandatory for Development
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
This package contains all necessary include files and libraries needed
to develop applications that require these.



%prep
%setup -q -n %{name}-%{version}

# gdbm-%{version}.dif
%patch0 -p1
# gdbm-protoize_dbm_headers.patch
%patch1 -p1
# gdbm-prototype_static_functions.patch
%patch2 -p1
# gdbm-fix_testprogs.patch
%patch3 -p1
# gdbm-destdir.patch
%patch4 -p1
# gdbm-stamp.patch
%patch5 -p1

%build
aclocal
autoreconf --force --install
export CFLAGS="$RPM_OPT_FLAGS -Wa,--noexecstack"

%configure --disable-static
make %{?jobs:-j%jobs}

%install
rm -rf %{buildroot}
%make_install

%remove_docs

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%doc COPYING
%{_libdir}/libgdbm.so.3
%{_libdir}/libgdbm.so.3.0.0

%files devel
%defattr(-,root,root,-)
%{_libdir}/libgdbm.so
/usr/include/gdbm.h
